# Generated by Django 3.2.3 on 2021-06-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0005_auto_20210516_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
