# Generated by Django 3.2.3 on 2021-06-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_photo'),
    ]

    operations = [
        migrations.RunSQL(
            "update auth_user set last_login = null where last_login is not null"
        ),
    ]
